---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: true
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - Messages
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - TV
  - Music
  - Podcasts
  - 'App Store'
dockitems_persist: 
  - name: "Xcodes"
    path: "/Applications/Xcodes.app/"
    pos: 12

# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_taps:
  - homebrew/bundle
  - homebrew/core
  - homebrew/cask

homebrew_use_brewfile: true

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 1547075542, name: "Decode" }
  - { id: 1459795140, name: "Klokki Slim" }
  - { id: 905953485, name: "NordVPN" }
  - { id: 967805235, name: "Paste" }
  - { id: 441258766, name: "Magnet" }
  - { id: 1289583905, name: "Pixelmator Pro" }
  - { id: 475772902, name: "Night Sky" }
  - { id: 899247664, name: "TestFlight"}
  - { id: 640199958, name: "Developer" }
  - { id: 568494494, name: "Pocket" }
  - { id: 1176895641, name: "Spark" }
  - { id: 904280696, name: "Things" }
  - { id: 747648890, name: "Telegram" }

mas_email: "overcot@yandex.ru"

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.

gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages:
  - beets # работа с музыкой
  - beautifulsoup4 # нужна для beets
  - virtualenv # виртуальные окружения python

# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
